### ISSUE TITLE
Are there any plans for Go-GSDK next?

### ISSUE THREAD

**Issue by flyinghail** [PlayFab/gsdk#113]
Is there a roadmap for Go-GSDK? I would like to know when it will be available for production environment.

**Comment by dgkanatsios** [comment]
thanks for reaching out and trying Multiplayer Servers! The only reason Go GSDK is experimental is that we still do not have a big number of users so it is not covered by our standard SLAs. However, we would love to help in its adoption so we'd be more than happy to provide support here on GitHub. The only exception to that is the "MarkAllocated" method, which is still not supported, but let us know if it's an issue for you

**Comment by flyinghail** [comment]
Thanks @dgkanatsios , I will try to use Go GSDK in my development and will give feedback if I encounter any problems.

**Comment by dgkanatsios** [comment]
Of course, let us know! Out of curiosity, what is the game engine you are using which requires the Go GSDK?

**Comment by flyinghail** [comment]
Currently it is for technology selection and testing, and is not determined.

**Comment by dgkanatsios** [comment]
Closing, since the question is answered, please create a new issue if you have any problems running the experimental Go GSDK.
