### ISSUE TITLE
Does not work with unreal engine 4.26 source

### ISSUE THREAD

**Issue by stefanospan** [PlayFab/gsdk#116]
VS2019 gives errors when compiling the project with the plugin inside, added plugin to plugins list and as module. Is any 4.26 version fine for this?

**Comment by dgkanatsios** [comment]
Is this for the Unreal GSDK?

**Comment by stefanospan** [comment]
Yeah sorry, looks like there are some random errors like HasField is not a shared member of TSharedPtr, PortObject cannot be used before its initialized etc.

**Comment by stefanospan** [comment]
Yes checked a few times

**Comment by nassosterz-ms** [comment]
The game instance should exist in your project, regardless of building the project with the Plugin. If you are creating a game of scratch and thus, there is not a GameInstance file, then the instructions show how to create it and go from there. 

I am not sure if this is relevant though, but it would be worth following all the instructions on the link I followed above and then following the build instructions to build the project. (You dont have to follow the Blueprint Implementation part if your project is from source).

**Comment by stefanospan** [comment]
As far as I know, and since the game instance can also be done from blueprints, it shouldnt affect in any way the compiling of the plugin. It seems to fail above though, a game instance wouldnt be possible to use functions from a plugin that isnt compiled either, so I dont think thats technically possible, especially if someone was following the blueprint approach of this since compiling is needed first. I can try following the steps again, but I checked it a few times already and it still wont work. There was an old GSDK integration for unreal which is down as well now, I guess thats not relevant anymore? Thaks

**Comment by nassosterz-ms** [comment]
Just wanted to provide an update. We have had couple of people test that they could build everything with 4.26 and they verified that they could successfully build the GSDK with UE4.26 source. Is there any update from your side?

**Comment by nassosterz-ms** [comment]
Closing this for now, given that UE5 was also released last week. If your issue persists, please open a new issue.
