### ISSUE TITLE
Missing blueprint UE4.27.2 Source and problem with plugins build

### ISSUE THREAD

**Issue by steini1993** [PlayFab/gsdk#122]
I have done almost everything after the book, but i had a problem with adding the Plugins code.
It would not compile with that code in there.

Even so when i deleted the plugins code, the build was doing just fine.

When in editor i see the plugin in plugins folder, and it is enabled.
So if the plugin is in the editor and enabled, it should be fine?

When i start with the blueprints section, i find RegisterGSDKhealthcheck and many other register nodes, but it is missing Ready for Players node.

Registerplayers node is there.

Anyone have some thoughts?

**Comment by steini1993** [comment]
Build started...
1>------ Build started: Project: BuildingProjectCpp, Configuration:
Development_Editor x64 ------
1>Using 'git status' to determine working set for adaptive non-unity build
(C:\UE_4.27.2).
1>Creating makefile for BuildingProjectCppEditor (.uproject file is newer)
1>UnrealBuildTool : error : Unhandled exception:
Tools.DotNETCommon.JsonParseException: Unable to parse
C:\Users\kirie\Documents\Unreal
Projects\BuildingProjectCpp\BuildingProjectCpp.uproject: Could not find
token at index 334
1>                           at
Tools.DotNETCommon.JsonObject.Read(FileReference File) in
C:\UE_4.27.2\Engine\Source\Programs\DotNETCommon\DotNETUtilities\JsonObject.cs:line
57
1>                           at
UnrealBuildTool.ProjectDescriptor.FromFile(FileReference FileName) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\System\ProjectDescriptor.cs:line
208
1>                           at
UnrealBuildTool.RulesCompiler.CreateProjectRulesAssembly(FileReference
ProjectFileName, Boolean bUsePrecompiled, Boolean bSkipCompile) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\System\RulesCompiler.cs:line
503
1>                           at
UnrealBuildTool.RulesCompiler.CreateTargetRulesAssembly(FileReference
ProjectFile, String TargetName, Boolean bSkipRulesCompile, Boolean
bUsePrecompiled, FileReference ForeignPlugin) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\System\RulesCompiler.cs:line
644
1>                           at
UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean
bSkipRulesCompile, Boolean bUsePrecompiled) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line
675
1>                           at
UnrealBuildTool.BuildMode.CreateMakefile(BuildConfiguration
BuildConfiguration, TargetDescriptor TargetDescriptor,
ISourceFileWorkingSet WorkingSet) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line
600
1>                           at UnrealBuildTool.BuildMode.Build(List`1
TargetDescriptors, BuildConfiguration BuildConfiguration,
ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference
WriteOutdatedActionsFile, Boolean bSkipPreBuildTargets) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line
257
1>                           at
UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line
226
1>                           at
UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in
C:\UE_4.27.2\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line
557
1>C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5):
error MSB3073: The command "C:\UE_4.27.2\Engine\Build\BatchFiles\Build.bat
-Target="BuildingProjectCppEditor Win64 Development
-Project=\"C:\Users\kirie\Documents\Unreal
Projects\BuildingProjectCpp\BuildingProjectCpp.uproject\""
-Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex
-FromMsBuild" exited with code 6.
1>Done building project "BuildingProjectCpp.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

I can build it without plugins code at the end, but not with the code.

{
"FileVersion": 3,
"EngineAssociation": "{2DDBE99C-406E-8159-07B3-528D13D5E0E9}",
"Category": "",
"Description": "",
"Modules": [
{
"Name": "BuildingProjectCpp",
"Type": "Runtime",
"LoadingPhase": "Default",
"AdditionalDependencies": [
"Engine"
]
}
],
   "Plugins": [                    // Add this if it doesn't exist
        {                           // Add this
            "Name": "PlayFabGSDK",  // Add this
            "Enabled": true         // Add this
        }                           // Add this
    ]                               // Add this if it doesn't exist
}

Even if i don't add this plugins code the plugin is in unreal editor and is
enabled for some reason. Because of that i wonder if i need this code at
all.

So when i build it without the code and i start with the blueprint part,
there was at last one blueprint missing. Since i can see the other
blueprints that is for playfab, i think i should have the plugin working,
if not i wouldn't have seen any of the playfab blueprints?

**Comment by nassosterz-ms** [comment]
To be clear, the blueprint implementation is not needed if the source code of the Plugin is properly integrated. Your .uproject file that you attached above seems fine. You may wanna right-click on it and select Generate Visual Studio Project Files and try to rebuild it.

One sanity check, have you added PlayFabGSDK on .Build.cs as the instructions show?

**Comment by steini1993** [comment]
Yes, I did. I dont know how many times i have read the documentation. it
didn't work, got a message.

**Comment by steini1993** [comment]
When i removed the plugins code it generate the files.

**Comment by steini1993** [comment]
Does this code look fine?

**Comment by steini1993** [comment]
{
	"FileVersion": 3,
	"Version": 1,
	"VersionName": "1.0",
	"FriendlyName": "PlayFabGSDK",
	"Description": "",
	"Category": "Other",
	"CreatedBy": "Nicholas Arthur",
	"CreatedByURL": "",
	"DocsURL": "",
	"MarketplaceURL": "",
	"SupportURL": "",
	"CanContainContent": true,
	"IsBetaVersion": false,
	"IsExperimentalVersion": false,
	"Installed": false,
	"Modules": [
		{
			"Name": "PlayFabGSDK",
			"Type": "Runtime",
			"LoadingPhase": "Default"
		}
	]
}

**Comment by steini1993** [comment]
{
	"FileVersion": 3,
	"Version": 1,
	"VersionName": "1.0",
	"FriendlyName": "PlayFabGSDK",
	"Description": "Unreal Integration of the PlayFab GSDK",
	"Category": "PlayFab",
	"CreatedBy": "Stefan Krismann",
	"CreatedByURL": "",
	"DocsURL": "",
	"MarketplaceURL": "",
	"SupportURL": "",
	"CanContainContent": false,
	"IsBetaVersion": true,
	"IsExperimentalVersion": false,
	"Installed": false,
	"Modules": [
		{
			"Name": "PlayFabGSDK",
			"Type": "Runtime",
			"LoadingPhase": "EarliestPossible"
		}
	]
}

**Comment by nassosterz-ms** [comment]
Which file is this?

**Comment by nassosterz-ms** [comment]
You bring a good point, it should be more clear in the documentation that GSDK can be integrated either by Source or with Blueprints. I am not sure how the order matters, but I am glad to hear that it worked.

**Comment by steini1993** [comment]
If you dont need the blueprint, do you still need the gameinstance where
you are suposed to set up the bp?

**Comment by nassosterz-ms** [comment]
Nope nothing blueprint related is needed, if there is a GameInstance.h / cpp file in the code then everything can happen through there. There is a sample GameInstance implementation provided.

**Comment by steini1993** [comment]
Ok, thanks for the clarification. I got an error in the packaging.

UATHelper: Packaging (Windows (64-bit)):     MyGameInstance.cpp.obj : error
LNK2005: "struct FLogCategoryLogPlayFabGSDK LogPlayFabGSDK"
(?LogPlayFabGSDK@@3UFLogCategoryLogPlayFabGSDK@@A) already defined in
Module.PlayFabGSDK.cpp.obj
UATHelper: Packaging (Windows (64-bit)):        Creating library
C:\Users\kirie\Documents\Unreal
Projects\BuildingProjectCpp\Binaries\Win64\BuildingProjectCpp.lib and
object C:\Users\kirie\Documents\Unreal
Projects\BuildingProjectCpp\Binaries\Win64\BuildingProjectCpp.exp
UATHelper: Packaging (Windows (64-bit)):
C:\Users\kirie\Documents\Unreal
Projects\BuildingProjectCpp\Binaries\Win64\BuildingProjectCpp.exe : fatal
error LNK1169: one or more multiply defined symbols found
UATHelper: Packaging (Windows (64-bit)): Took 43.675737s to run
UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log
for more details.
(C:\UE_4.27.2\Engine\Programs\AutomationTool\Saved\Logs\UBT-BuildingProjectCpp-Win64-Development.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with
ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error

Any ideas?

**Comment by nassosterz-ms** [comment]
Yup the fix for this was merged yesterday, you can view the new documentation about it, found here:
https://github.com/PlayFab/gsdk/blob/main/UnrealPlugin/ThirdPersonMPGSDKSetup.md

**Comment by nassosterz-ms** [comment]
If this is bringing you troubles, you can just use LogTemp as Log channel. In that case, get rid of the DECLARE_LOG_CATEGORY_EXTERN on the .h and the DEFINE_LOG_CATEGORY on the .cpp and just have all your logs take LogTemp rather than the one defined in the documentation.

**Comment by nassosterz-ms** [comment]
Replace every instance of LogPlayFabGSDK with LogTemp and it should work.

**Comment by steini1993** [comment]
Playfab.uplugin
