### ISSUE TITLE
Request to disable heartbeats/plugin functionality with a variable.

### ISSUE THREAD

**Issue by sonicphi** [PlayFab/gsdk#127]
It would be good for debugging and for portability to be able to simply disable the plugins functionality with a global variable some how.

If i want to send the server .exe to a friend so that he can run the server on his machine i have to disable the plugin and delete all related blueprints every time and this is very time consuming/annoying.

Also, if you want to have a server browser with players hosting sessions on their machines i believe that is not currently possible because the game will always be looking for the heartbeats and it will just crash if you don't run the server on the playfab agent? correct me if i am wrong but i found nothing on this in the docs.

So i would assume that disabling the plugin functionality somehow would allow for those sessions to be created normally and for the .exe to run like a regular ue4 server .exe .

**Comment by nassosterz-ms** [comment]
This variable exist. 

In your game project, there is a .uproject file. In that, per the instructions to enable the GSDK you have to add the following:

"Plugins": [
	{
		"Name": "PlayFabGSDK",
		"Enabled": true
	}
]

If you set "Enabled": false, then you will achieve what you want. Building and packaging your game / server will ignore the GSDK.

**Comment by sonicphi** [comment]
I have not tested this but i assume this is the same as disabling it in the editor right? if that is the case i would still have the same problem of having to delete all the nodes and then making them again when i want the plugin back on.

**Comment by haydenstech** [comment]
You can achieve this functionality with a command line arg, I've got it setup on a local project and it works fine, will submit a PR later tonight 👍

**Comment by sonicphi** [comment]
> You can achieve this functionality with a command line arg, I've got it setup on a local project and it works fine, will submit a PR later tonight 👍

Excuse my ignorance but whats a PR? 

Also u mean a command line argument like the "-log" you put after the .exe in the shortcut so that the log window shows?

**Comment by dgkanatsios** [comment]
@sonicphi, check here for the PR definition, let us know if you have any more question!

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

@haydenstech, excited for the PR, thanks in advance!

**Comment by haydenstech** [comment]
@sonicphi Yes exactly, "-nogsdk" is the argument name I use

and no worries @dgkanatsios 👍 Glad to be able to contribute

**Comment by haydenstech** [comment]
Hi all, 
Pull request is as above, can provide some examples on usage at a later date if required 👍 

Cheers
