### ISSUE TITLE
UE 5.1.1 "Heartbeat endpoint and Server id are required configuration values"

### ISSUE THREAD

**Issue by subwooferx3** [PlayFab/gsdk#149]
Hello, using a source build of the most recent Unreal Engine 5.1.1 build, I followed all tutorials and all github issues and forum posts to try and squash this fatal error message "Heartbeat endpoint and Server id are required configuration values" when running my server through LocalMultiplayerAgent. I've tried every combination of file structures, game port names, port numbers, including DLL's, and such with the same error causing the server to crash after mounting all plugins.

I was getting ready to call it quits on the integration entirely, when I decided to upload the server build to playfab directly as a final test. To my surprise, the server completely works on playfabs end and I was even able to connect with a friend which was a massive relief but still leads me to wonder what is causing so many issues with testing it locally.

This is what my MultiplayerSettings.json currently looks like (titleID and gamename redacted), however I have tried many configurations whether they were the defaults it came with, I tried the "Huli" configuration guide that shows up when you google, I've used the settings generator and I've tried every game port name I could find to no avail. I usually run it as a windows process as I have never set up anything in regards to Docker, and I do indeed see the process run in task manager before it instantly closes and logs to gamelogs.

{

    "AssetDetails": [
        {
            "LocalFilePath": "C:\\Users\\alexw\\Videos\\GameBuilds\\GameServerTest.zip"
        }
    ],
    "PortMappingsList": [
        [
            {
                "GamePort": {
                    "Name": "gameport",
                    "Number": 7777,
                    "Protocol": "UDP"
                },
                "NodePort": 56100
            }
        ]
    ],
    "GameCertificateDetails": [],
    "SessionConfig": {
        "SessionCookie": null,
        "SessionId": "af240ab0-9c7f-43b8-9630-d79db3b5cc8e",
        "InitialPlayers": [
            "Player1",
            "Player2"
        ]
    },
    "DeploymentMetadata": {
        "Environment": "LOCAL",
        "FeaturesEnabled": "List,Of,Features,Enabled"
    },
    "TitleId": "0",
    "Region": "EastUs",
    "BuildId": "28fb75f8-cad1-4908-b5d4-0a2e37bcc71e",
    "RunMode": 0,
    "ProcessStartParameters": {
        "StartGameCommand": "GameServerTest\\Binaries\\Win64\\GameTestServer.exe -log"
    },
    "OutputFolder": "GameLogs",
    "NumHeartBeatsForActivateResponse": 10,
    "NumHeartBeatsForTerminateResponse": 172800,
    "AgentListeningPort": 56001
}

**Comment by dgkanatsios** [comment]
the error message seems to indicate that the GSDK config file cannot be found. Can you see one created in the output path, where your game server should be located?

**Comment by subwooferx3** [comment]
Yes, there is one generated

```
{

  "heartbeatEndpoint": "127.0.0.1:56001",
  "sessionHostId": "128a3e9d-671d-4e65-b99c-2de8d6f14b98",
  "vmId": "xcloudwusu4uyz5daouzl:EastUs:482df656-b461-40e5-be02-a3fff2a2115f:tvmps_f0aee7d924d1496392c51ad4b7e65aef4d7eb7faf0d74c76ab5d8c25f6bce3ea_d",
  "logFolder": "GameLogs\\PlayFabVmAgentOutput\\2023-06-05T12-00-09\\GameLogs\\128a3e9d-671d-4e65-b99c-2de8d6f14b98",
  "certificateFolder": "GameLogs\\PlayFabVmAgentOutput\\2023-06-05T12-00-09\\GameCertificates",
  "sharedContentFolder": "GameLogs\\PlayFabVmAgentOutput\\2023-06-05T12-00-09\\GameSharedContent",
  "buildMetadata": {
    "Environment": "LOCAL",
    "FeaturesEnabled": "List,Of,Features,Enabled"
  },
  "gamePorts": {
    "gameport": "56100"
  },
  "publicIpV4Address": "127.0.0.1",
  "gameServerConnectionInfo": {
    "publicIpV4Adress": "127.0.0.1",
    "gamePortsConfiguration": [
      {
        "name": "gameport",
        "serverListeningPort": 56100,
        "clientConnectionPort": 56100
      }
    ]
  },
  "fullyQualifiedDomainName": "localhost"
}
```

**Comment by nassosterz-ms** [comment]
Hello.

I do not know exactly how it matters but the MultiplayerSettings.json that is included here is missing some fields like: RunContainer.

Also, for sanity, could you replace the relative path of StartGameCommand with an absolute path and retest?

Finally, is the zip file in LocalFilePath valid?

**Comment by subwooferx3** [comment]
As stated in the original post I have tried all mixes of settings and most of my attempts were with the one that had runcontainer set to false. 
Just to make sure I tested right now with runcontainer set to false, the absolute path, both the .exe in the main folder and the binaries/win64 folder and they both had the same error. I do see the server .exe boot up for a few seconds before it force closes

**Comment by nassosterz-ms** [comment]
Any chance you could attach here the server log? Also, any logs generated by the LMA tool may also be helpful. (You may need to remove the titleId from the logs)

**Comment by subwooferx3** [comment]
[GameServerServerLogs.txt](https://github.com/PlayFab/gsdk/files/11656068/GameServerServerLogs.txt)
[GameServerUnrealCrash.log](https://github.com/PlayFab/gsdk/files/11656069/GameServerUnrealCrash.log)

**Comment by nassosterz-ms** [comment]
I looked at the generated config you pasted and compared it with one from my local testing and things look correct.

I am thinking it could be a path issue. Could you attach a debugger into the GSDK code with Visual Studio and could you see the value of FileName at line 21 of GSDKInternal.cpp. Alternatively, you can add:

**Comment by subwooferx3** [comment]
Having added those logs, the outputs appear to be entirely blank. My best guess at this point is that the GetEnvironmentVariable function is just entirely not working but I'm not sure what to do about that myself
```
LogPlayFabGSDK: The HEARTBEATENDPOINT value is: 
LogPlayFabGSDK: The SERVERID value is: 
LogWindows: Error: appError called: Fatal error: [File:C:\Users\alexw\Documents\GitHub\GameServer\Plugins\PlayFabGSDK\Source\PlayFabGSDK\Private\GSDKInternal.cpp] [Line: 69] 
Heartbeat endpoint and Server id are required configuration values.
```

**Comment by nassosterz-ms** [comment]
Could you also try printing FileName at line 21 of GSDKInternal.cpp? My gut tells me there is something wrong with the path on the MultiplayerSettings.json file. Since everything is working when you upload your server on PlayFab, that makes it even more plausible.

Is this the StartCommand you use on PlayFab also:  "StartGameCommand": "GameServerTest\\Binaries\\Win64\\GameTestServer.exe -log"?

**Comment by subwooferx3** [comment]
printing out the filename returns this:

```
LogPlayFabGSDK: The FileName value is: GameLogs\PlayFabVmAgentOutput\2023-06-06T12-46-43\Config\SH0\gsdkConfig.json
LogPlayFabGSDK: The HEARTBEATENDPOINT value is: 
LogPlayFabGSDK: The SERVERIDKEY value is: 
```

and the config found in that folder is
```
{
  "heartbeatEndpoint": "127.0.0.1:56001",
  "sessionHostId": "1009cc23-273c-409b-b666-15873c4fbd9b",
  "vmId": "xcloudwusu4uyz5daouzl:EastUs:d20d7728-9c9f-4abd-9cc7-cf95bb4c90ab:tvmps_63a3ed760e8f44b69ed433ce0f35f5dc32a0217f9f4642328a24bb2b03a4799c_d",
  "logFolder": "GameLogs\\PlayFabVmAgentOutput\\2023-06-06T12-46-43\\GameLogs\\1009cc23-273c-409b-b666-15873c4fbd9b",
  "certificateFolder": "GameLogs\\PlayFabVmAgentOutput\\2023-06-06T12-46-43\\GameCertificates",
  "sharedContentFolder": "GameLogs\\PlayFabVmAgentOutput\\2023-06-06T12-46-43\\GameSharedContent",
  "buildMetadata": {
    "Environment": "LOCAL",
    "FeaturesEnabled": "List,Of,Features,Enabled"
  },
  "gamePorts": {
    "gameport": "56100"
  },
  "publicIpV4Address": "127.0.0.1",
  "gameServerConnectionInfo": {
    "publicIpV4Adress": "127.0.0.1",
    "gamePortsConfiguration": [
      {
        "name": "gameport",
        "serverListeningPort": 56100,
        "clientConnectionPort": 56100
      }
    ]
  },
  "fullyQualifiedDomainName": "localhost"
}
```

the command I use to start on playfab is  "GameServerTest\Binaries\Win64\GameTestServer.exe -log", upon trying just "GameTestServer.exe -log" the server failed to start on playfabs side aswell as the localmultiplayeragent side with the same error.

**Comment by nassosterz-ms** [comment]
Well the filename looks valid. Any chance you could add a couple more loggers?

Inside the if statement: if (!FPaths::FileExists(FileName))
See if you could add a logger that says that the file exists. That will probably eliminate that there is a path issue.

**Comment by subwooferx3** [comment]
Adding 
```
	if (!FPaths::FileExists(FileName))
	{
		UE_LOG(LogPlayFabGSDK, Log, TEXT("FileName does NOT exist"));
		ConfigPtr = MakeUnique<FEnvironmentVariableConfiguration>();
	}
```
returns 
`LogPlayFabGSDK: FileName does NOT exist`
when the localmultiplayeragent is ran. The ! not symbol in the if confused me when I first compiled but the else statement would have printed "FileName DOES exist"

**Comment by nassosterz-ms** [comment]
Hmm, on your MultiplayerSettings.json: https://github.com/PlayFab/gsdk/issues/149#:~:text=%22OutputFolder%22%3A%20%22GameLogs%22%2C

Could you make it an absolute path and retest?

**Comment by subwooferx3** [comment]
Wow, after everything I've tried I can't believe that changing the OutputFolder to an absolute path was gonna be the thing that fixed it, even though I swear I tried it before. I'm sure it was a cumulative effort of that and the other changes I've made to the settings json.
It completely works, lets me connect and everything, thank you so much for your help! That was the last thing that was making me pull out my hair, I had no idea what I was doing wrong.

**Comment by subwooferx3** [comment]
Bumping this real quick to just add an update for anyone who finds this issue and still can't fix it, having switched to linux builds I realized I changed
`FGenericPlatformMisc::GetEnvironmentVariable(*EnvironmentVariableName);`
in SDKInternalUtils.cpp (9) to
`FWindowsPlatformMisc::GetEnvironmentVariable(*EnvironmentVariableName);`
going back to windows builds I was getting the same error locally testing until I changed this back to windowsplatformmisc and recompiled my project and now it successfully tests locally
