### ISSUE TITLE
VMId not being updated from environmental variable

### ISSUE THREAD

**Issue by sumopandian** [PlayFab/gsdk#161]
**Describe the bug**
The function UGSDKUtils::GetVMId() in the unreal plugin returns an empty string

**To Reproduce**
Call UGSDKUtils::GetVMId() on a deployed playfab server.

**Expected behavior**
We expect the actual unique VMId of the server to be returned.

Occurs on the latest version.

**Additional context**
The PF_VM_ID environmental variable seems to be never used in the code.

**Comment by dgkanatsios** [comment]
thanks for opening this @sumopandian, we'll take a look soon! FYI @tculotta

**Comment by dgkanatsios** [comment]
As a workaround, folks can grab the PF_VM_ID environment variable directly (https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/servers/basics-of-a-playfab-game-server#server-scripts-and-playfab-configured-environment-variables)
