### ISSUE TITLE
Unreachable Code during compilation for UE 5.4.1

### ISSUE THREAD

**Issue by VoidConcepts** [PlayFab/gsdk#171]
**Describe the bug**
A new project built from source for Unreal Engine 5.4.1 will not build when trying to integrate the PlayFabGSDK plugin.
After adding it to the project:

"UnrealPlugin/Source/PlayFabGSDK/Private/PlayFabGSDK.cpp"
On line 136 and 146 Visual Studio 2022 return errors, "Unreachable Code."

**To Reproduce**
Follow the integration steps for an unreal project using UE 5.4.1 (Source).

**Expected behavior**
I expected the project to build as normal. Similarly to my project using UE 5.3.2

**Screenshots**
This is the Original Code.
![Original](https://github.com/PlayFab/gsdk/assets/138183709/88f525a0-5622-425e-9906-1563e174ee06)

This is what I edited it too.
![Edited](https://github.com/PlayFab/gsdk/assets/138183709/ddd7eb76-ad3f-4057-9084-2dca2a756665)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version: 23H2

**Additional context**
Added an, "#else", and moved the, "#endif".  which **at least** let me build my project for the Editor, Client, & Server, targets.
Haven't tested any further than this.

**Comment by tculotta** [comment]
Thanks you for this catch! We haven't officially tested 5.4 support yet, so please do submit issues for anything else you find in the meantime.
