### ISSUE TITLE
Assets\PlayFabSDK\MultiplayerAgent\Model\SessionConfig.cs(72,18): error CS0019: Operator '+' cannot be applied to operands of type 'int' and 'bool'

### ISSUE THREAD

**Issue by SniperED007** [PlayFab/gsdk#46]
Created a new unity project, added PlayFab and the PlayFab Game Server SDK

Throws the followings script error:
Assets\PlayFabSDK\MultiplayerAgent\Model\SessionConfig.cs(72,18): error CS0019: Operator '+' cannot be applied to operands of type 'int' and 'bool'

**Comment by dgkanatsios** [comment]
Thanks for reporting that, @SniperED007. Should I assume that this is from the latest gdsk that we merged yesterday?

**Comment by SniperED007** [comment]
Yes.

**Comment by dgkanatsios** [comment]
Cool, we’ll take a look ASAP. In the meantime, can you use a GetHashCode implementation from [here](https://stackoverflow.com/questions/263400/what-is-the-best-algorithm-for-overriding-gethashcode) and let us know if it works for you?

**Comment by SniperED007** [comment]
to fix it I changed the code from:

hashCode = hashCode * -1521134295 + EqualityComparer<Dictionary<string, string>>.Default.Equals(Metadata);
to
hashCode = hashCode * -1521134295 + EqualityComparer<Dictionary<string, string>>.Default.GetHashCode(Metadata);

**Comment by dgkanatsios** [comment]
Fixed, thanks for letting us know!
