### ISSUE TITLE
Unity Multiplayer Server's heartbeat vanishes 

### ISSUE THREAD

**Issue by MScottAdams** [PlayFab/gsdk#49]
From https://github.com/PlayFab/UnitySDK/issues/226

Been chasing an issue where our game server loses its heartbeat. Our server actually switches scenes during its startup.

Root cause is missing code in PlayFabMultiplayerAgentView

Adding the following to the class fixed the issue:

```csharp
public class PlayFabMultiplayerAgentView : MonoBehaviour
{
private float _timer;
/// <summary>
/// Awake constructor
/// </summary>
private void Awake()
{
    Debug.Log($"{Time.fixedTime} PlayFabMultiplayerAgentView awake ");

    // Need to keep this game object alive through scene changes.
    DontDestroyOnLoad(this);
}

/// <summary>
/// Called when gameobject is destroyed
/// </summary>
private void OnDestroy()
{
    Debug.Log($"{Time.fixedTime} PlayFabMultiplayerAgentView destroyed ");
}
```

**Comment by dgkanatsios** [comment]
thank you!

**Comment by MScottAdams** [comment]
Welcome! Sorry but I tried a couple of times but can't get the code indicators in the sample above working.  It's probably easier to read it in original post on Unity SDK.

**Comment by dgkanatsios** [comment]
I think I fixed that, let me know if code looks like intended now.

**Comment by MScottAdams** [comment]
Thanks that is correct now!

**Comment by dgkanatsios** [comment]
Coming back to this, want to make a pull request on this repo adding the `DontDestroyOnLoad` method? We'd be more than happy to review, discuss and accept!

**Comment by MScottAdams** [comment]
Sorry as I mentioned before I just don't have the time currently to setup GIT and do all the required steps.

**Comment by CaptainPineapple** [comment]
I'd go a bit further and suggest a singleton approach since depending on the scenes setup a scenechange might result in multiple Object getting created. Thus i'd suggest to add these following changes instead:

`
public class PlayFabMultiplayerAgentView : MonoBehaviour
{
    public static PlayFabMultiplayerAgentView current;
    private float _timer;
    /// <summary>
    /// Awake constructor
    /// </summary>
    private void Awake()
    {
        Debug.Log($"{Time.fixedTime} PlayFabMultiplayerAgentView awake ");
        // Check if the static instance already contains a refernce:
        if (current)
        {
            // Destroy this instance since we only ever need one PlayFabMultiplayerAgentView
            Destroy(gameObject);
            return;
        }
        else
        {
            // Need to keep this game object alive through scene changes.
            DontDestroyOnLoad(this);
            current = this;
        }
    }

    /// <summary>
    /// Called when gameobject is destroyed
    /// </summary>
    private void OnDestroy()
    {
        Debug.Log($"{Time.fixedTime} PlayFabMultiplayerAgentView destroyed ");
    }
}
`

**Comment by dgkanatsios** [comment]
I believe we can close this due to #52, thanks @MScottAdams for bringing this up and @CaptainPineapple for the PR!
