### ISSUE TITLE
Playfab Admin Models do not include West Us

### ISSUE THREAD

**Issue by MScottAdams** [PlayFab/gsdk#50]
The PlayFabAdminModels.cs  region enum does not include the West US just EuWest.

    public enum Region
    {
        USCentral,
        USEast,
        EUWest,
        Singapore,
        Japan,
        Brazil,
        Australia
    }

**Comment by dgkanatsios** [comment]
I think you're referring to a Unity PlayFab SDK file. The Unity PlayFab SDK was removed from Unity GSDK a couple of commits ago. You can pull and use Unity PlayFab SDK from its own repo [here](https://github.com/PlayFab/UnitySDK).

**Comment by MScottAdams** [comment]
Moved to https://github.com/PlayFab/UnitySDK/issues/229
