### ISSUE TITLE
Assets\PlayFabSDK\MultiplayerAgent\PlayFabMultiplayerAgentView.cs(40,17): error CS0103: The name 'PlayFabMultiplayerAgentAPI' does not exist in the current context

### ISSUE THREAD

**Issue by hengkyz** [PlayFab/gsdk#55]
**Describe the bug**
After import the GSDK unity package
it shows this error 
Assets\PlayFabSDK\MultiplayerAgent\PlayFabMultiplayerAgentView.cs(40,17): error CS0103: The name 'PlayFabMultiplayerAgentAPI' does not exist in the current context

**Comment by hengkyz** [comment]
i just fixed it, look like the getting start define symbol and the package is different
in the getting started tutorial, its said that need to add #if ENABLE_PLAYFAB_SERVER_API
but in the code it use #if ENABLE_PLAYFABSERVER_API (without "_" symbol )

**Comment by dgkanatsios** [comment]
Thank you - would you like to submit a Pull Request so we can fix it in the repo? We’d be more than happy to help!

**Comment by hengkyz** [comment]
ok sir, ill create pull request

**Comment by dgkanatsios** [comment]
Thank you!
