### ISSUE TITLE
GSDK - Session Cookie Updated Event

### ISSUE THREAD

**Issue by darvell** [PlayFab/gsdk#61]
**Is your feature request related to a problem? Please describe.**
When a server is created with a session cookie, it is usually not until a couple heartbeats that the cookie is available.

**Describe the solution you'd like**
An event that fires when the session cookie has been updated.

**Describe alternatives you've considered**
I currently have my GSDK modified to do this but it's quite messy. Alternatively it'd be interesting to know why the session cookie isn't there from the start, could this maybe be better done as an environment variable so it's there from the start?

**Additional context**
Developers creating servers sometimes want to put certain game info in there and can easily fall in to the trap of expecting that the session cookie to be available from the start of initializing the GSDK.

**Comment by dgkanatsios** [comment]
are you referring to the `SessionCookie` parameter of the [RequestMultiplayerServer](https://docs.microsoft.com/en-us/rest/api/playfab/multiplayer/multiplayerserver/requestmultiplayerserver?view=playfab-rest) API call? When this API is called, the ReadyForPlayers() is unblocked (or its callback is triggered, depending on your GSDK platform) and is available to you. If you want some custom metadata to be available before ReadyForPlayers(), you can use custom metadata when you [create your Build](https://docs.microsoft.com/en-us/rest/api/playfab/multiplayer/multiplayerserver/createbuildwithcustomcontainer?view=playfab-rest)

**Comment by darvell** [comment]
There are going to be cases where one needs the metadata before being ready for players, for example if you are loading a specific scene in standby based off the session cookie, you should alerted that it's value has changed. I'd even argue a lot of the state changes that come from the heartbeat should be firing off events, I understand not everyone has a use for it but assuming if I were to write a PR, it wouldn't hurt right?
