### ISSUE TITLE
vcpkg and cmake support

### ISSUE THREAD

**Issue by jseward** [PlayFab/gsdk#69]
Making a linux build of this library that is compatible with how my server app is built on linux is painful. The easiest solution would be if I could use https://github.com/microsoft/vcpkg to generate the linux library. Thanks.

1. add cmake support so I can build in a custom linux environment without being forced to go through visual studio
2. add this project to https://github.com/microsoft/vcpkg

**Comment by dgkanatsios** [comment]
Thanks for opening the issue! We’ll take a look soon!

**Comment by jseward** [comment]
Here are the contents of my super simple and naive `CMakeLists.txt` that seems to work for now.

```
cmake_minimum_required(VERSION 3.14)

add_library(GSDK_CPP_Linux
    gsdk.cpp
    gsdkConfig.cpp
    gsdkLog.cpp
    gsdkUtils.cpp
    jsoncpp.cpp
    ManualResetEvent.cpp
)

set_target_properties(GSDK_CPP_Linux PROPERTIES
    CXX_STANDARD 17
)

target_compile_options(GSDK_CPP_Linux PRIVATE -stdlib=libc++)   
target_compile_options(GSDK_CPP_Linux PRIVATE
    -DGSDK_LINUX
)

target_include_directories(GSDK_CPP_Linux PRIVATE
    "."
)
```

**Comment by dgkanatsios** [comment]
Thanks @jseward ! Would you like to make a PR with this? We’d be more than happy to review and merge!

**Comment by dgkanatsios** [comment]
Closing since #70 was merged
