### ISSUE TITLE
Instructions unclear for UE4 integration

### ISSUE THREAD

**Issue by MatthewSbar** [PlayFab/gsdk#84]
Nevermind

**Comment by dgkanatsios** [comment]
Hey @MatthewSbar, did you figure out the solution to the issue? Let us know if we can help in any way

**Comment by MatthewSbar** [comment]
Yes, feel free to delete this issue. I got to the step in the documentation about including the custom game instance but hadn't read ahead to see what edits were necessary to actually create the game instance. I would possibly re-order these in the documentation so it doesn't feel like the reader missed a step, but, it is all there assuming one reads ahead, so it's kind of a non-issue.
