### ISSUE TITLE
Remove sample from Unity GSDK

### ISSUE THREAD

**Issue by dgkanatsios** [PlayFab/gsdk#89]
Remove sample from Unity GSDK https://github.com/PlayFab/gsdk/tree/master/UnityGsdk/Assets/MultiplayerServerSample

**Comment by roestzwiee** [comment]
But why? I was glad to have it found!

**Comment by roestzwiee** [comment]
I got it, cuz there is a newer one:
https://github.com/PlayFab/MpsSamples/tree/master/UnityMirror

**Comment by dgkanatsios** [comment]
This was done in #119
